env:
  global:
    - MAGE2_FAKE_URL=http://magento-2-ce.dev
    - MAGE2_ADMIN_EMAIL=inf@emico.nl
    - MAGE2_ADMIN_FIRST_NAME=Emico
    - MAGE2_ADMIN_LAST_NAME=Emico
    - MAGE2_ADMIN_USERNAME=admin
    - MAGE2_ADMIN_PASSWORD=admin123
    - MAGE2_DB_NAME=magento_2
    - MAGE2_DB_USER=travis
    - MAGE2_DB_HOST=127.0.0.1
    - MAGE2_DB_PASSWORD=
  matrix:
    - MAGE2_VERSION=2.1 TEST_SUITE=unit
    - MAGE2_VERSION=2.1 TEST_SUITE=acceptance
    - MAGE2_VERSION=2.0 TEST_SUITE=unit
    - MAGE2_VERSION=2.0 TEST_SUITE=acceptance

matrix:
  allow_failures:
    - php: 7.1

language: php

dist: trusty

php:
  - 7.0
  - 7.1

addons:
  hosts:
    - magento-2-ce.dev

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - ./tests/setup/composer.sh
  - ./tests/setup/database.sh
  - ./tests/setup/magento.sh
  - cd /tmp/build

script:
  - ./vendor/emico/tweakwise-export/vendor/bin/codecept run -c vendor/emico/tweakwise-export/codeception.yml $TEST_SUITE