env:
  global:
    - MAGE2_FAKE_URL=http://magento-2-ce.dev
    - MAGE2_ADMIN_EMAIL=inf@emico.nl
    - MAGE2_ADMIN_FIRST_NAME=Emico
    - MAGE2_ADMIN_LAST_NAME=Emico
    - MAGE2_ADMIN_USERNAME=admin
    - MAGE2_ADMIN_PASSWORD=admin123
    - MAGE2_DB_NAME=magento_2
    - MAGE2_DB_USER=travis
    - MAGE2_DB_HOST=127.0.0.1
    - MAGE2_DB_PASSWORD=
    # MAGENTO_TOKEN_PUBLIC
    - secure: "Utv4T9zI73AOmOHsPNyESZt4LyDXzRRSqgO+Ah2BWjBqa6pktD1gmEaOyGDzIsZIuXxPIPslXdoUvy9xOmEeOBN2scCD/JN71KVnNVdT+VSexDSS1DSLIx4dLopugOjuBsbBJeXwWkdiSxP1UQAsrJhBfupAS9lbbeeFuN7gTX6YmnypQmNiNAnzsvlsparnp6KnjZcxb3l2nCQNJLVi5IObfIFEsiXDhNedZTj0sIHYog8CRJn5HwnqwQMlY8hf1c383O7AcCXqiMUNTRAPMgeN2cd4+gm3T1xCIDDk35cbRCe0yR391gt5CYd9PQMHYOJhJBEUBCBE4blc3qaByaffbszsuijvPzmPUAsVUNRcOt6KYQ6NEVchWaInnYmuRZ0RgZXeSKxyopM0EOvroLIRoM1smXJa+YfeOjRYwbfVLUeZDZCnCyER7K/UgIn6G/p3UrtJGdaRNT3L636vQi7/7Uz3MCK02PI+omgIRZtZhU/QJ98UM2yMiU/kklACyqNJuPC/zDIX17NVx2dqC1DeggLdAR7RfL9Eyg6vKxbbwoiRgOhKMqWsBCz9IP9eKDhg1ZjYtSE8Ksk5cV6J/gsgkSOyRY/aiQ3xICiER0jOp3dj3kg3K3kl5Awe1/NEok2Xbudt1WZPGVUbT6PA5HsvuU7t6a2MUq7UHYTuDlk="
    # MAGENTO_TOKEN_PRIVATE
    - secure: "R7g9QD3CvO9l/ne+fqngYyMbLXoFK2X7rfaNm3TSChqT0211N1OveV5BELXQi/fErC6iTvBT2bfSxe3hBomxgCrjsGfqTzsoHIfHAs0ijluWAbbPEYTAoviNpwZnlB1gKiIubBSf4bZHEVDaxL2VCrz/SIbEm+dFSgbvrjogzyBBiAbWHnJr2UGKGc/ZsH4V3ImuL4Pq/22FvFb3up28OdexxhJ4XGSIcytp90j3qBnb92LXXVe8uzvmz3EbVf1dcul3YhqHRoVwPsocuQWIJV86ol2BC7bhGNvTeOdX2P2an4ZsKQKcDl5OkVC0J+37Mrclov+MowIZFgjxZwYopyb/rlHqjA+y0/IchdULkHBg2jQghdEfZw+hSnTTLCaqHRNAXhJYvcJc8Yb0IdSy9XXD3W2QZdRA/bylAk81QdxzPmRrUnU1TL4/u5s/bSJkbXrqnL8Oh7bMgKhEjyPI5bbqHDFjoyq2lDuQmftUS/kPwNQyq7jHlWQ2gVEfvcHhlmzN22zWfLRt+vg8hKpqXdgVlNHCbf3I23lKcfWM8t5fLf9886RgnJiffEOQA77msLj/CfxZe38XJ9dll9+iUElRbC0IuLaM/a8OmCe1rkLUPTDplUTrkdQYq+SknyPaXxsIadrTLXTlQ3MeRe5mZeDcPFiJAQW07y0AJzf4D7k="
    # GITHUB_TOKEN
    - secure: "WiNLOXtLlpmwtbKq9vNSilxBVI1pUiwpm/cv7bNAJ+nbKxsdqSSdcDTPBehTH/6xPiya06rEHNAar5s30ebA3ic19SvWMpRBo7qVkfNQ8cli3/tSS4LqS1WpA1RDf/wUdeKCLYxi5iXY1pMDLnpY7GBvQzmCrXcJ6ANBXovtkNuPXq1PUq8hUmGfuCDh2Qr0er99jclQoZ4alwe6yjENorKqIJy5qzMAH7v5gqKqifrrZzm7YU7O2rNFqm3SsizfBAowgO2c4z2F6M15ucLrJDOuWIRovNSWzBA/xUbCrKSFHI4bG0x57K+vlBx+46uuVwgjzmQEncx4jQTix6PmeBIGybrGvTlgFT+OUEBEk6iWSkQRWEcE76o9zyxvNvp7S4LbO0LaF7Sa9fjJd0LBCiZ6gcET0sMXmJsRd7Dl5c8MwCJWpLZbgdr/FnDDNSBslQc9bwx7OpPzF6ibTZ08ICvXwG1G4hm6ZPmIjIiRvJKR1lyT6C6Bavln9xvtnKDKdudEWEg7nBLbRtfKTVIbBQb56lCQkhs4MKDW+ZAHnAu9D53XgE2J64HKeoPY20T4t/QjanQn9DK/UQREFNVtYk0YOH4NBtx42keYbdKHSo72EhKyOSeuQff7YcGq3qAHW6Nxx0JyV1ewwuoY5jGeJus4/IAjUwdgMOzP22rxwIw="

  matrix:
    - MAGE2_VERSION=2.1 TEST_SUITE=unit
    - MAGE2_VERSION=2.1 TEST_SUITE=acceptance
    - MAGE2_VERSION=2.0 TEST_SUITE=unit
    - MAGE2_VERSION=2.0 TEST_SUITE=acceptance

matrix:
  allow_failures:
    - php: 7.1

language: php

dist: trusty

php:
  - 7.0
  - 7.1

addons:
  hosts:
    - magento-2-ce.dev

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - ${TRAVIS_BUILD_DIR}/tests/setup/composer-configure.sh --global
  - ${TRAVIS_BUILD_DIR}/tests/setup/composer-install.sh
  - ${TRAVIS_BUILD_DIR}/tests/setup/magerun2.sh
  - ${TRAVIS_BUILD_DIR}/tests/setup/database.sh
  - ${TRAVIS_BUILD_DIR}/tests/setup/magento.sh
  - ${TRAVIS_BUILD_DIR}/tests/setup/package.sh

script:
  - cd /tmp/build
  - php bin/magento setup:di:compile
  - ./vendor/emico/tweakwise-export/vendor/bin/codecept run -c vendor/emico/tweakwise-export/codeception.yml $TEST_SUITE
